### PR TITLE
Upgraded code as of manifest v3

### PR DESCRIPTION
**Pull request by ziedHamdi**
Still needs to be moved from _archive/mv2 to mv3. Also the [tutorial](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/) link to it should be updated

### CODE REVIEW

**Comment by jpmedley** [comment]
@ziedHamdi Thank you for your contribution. Can you please sign the appropriate contributor license agreement as described on our [contributing page](https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/CONTRIBUTING.md). We're not allowed to merge from anyone who doesn't have one on file.

Thanks

**Comment by ziedHamdi** [comment]
Hi Joe,

I just signed it. Please reach back to me if something was done wrong.

Best regards,

*Zied Hamdi*
*Founder & CEO*
linkedin.com/in/weally <http://www.linkedin.com/in/weally>
***@***.*** ***@***.***> ◄► http://weally.org <http://weally.org>*
*+420 70 21 22 21 6 (also on WhatsApp & Telegram)*

**Comment by patrickkettner** [comment]
Thanks @ziedHamdi!
Can you merge in the current state of the repo? We added Prettier and would be great to get those auto changes taken care of

**Comment by oliverdunk** [comment]
I'm going to close this for now. If you'd like to re-open merged with `main` and moving out of the `mv2` folder though, I'd be happy to take another look.

**Pull request closed without merging**
