### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by AdamCanady**

### CODE REVIEW

**Comment by AdamCanady** [comment]
this typo still exists?

**Comment by samthor** [comment]
We're doing some bug bankruptcy and restructuring. If you can rebase your PR against the moved folder we'll accept it.

**Comment by AdamCanady** [comment]
done!

**Review by samthor — APPROVED** [review]

**Review by Pakinay — COMMENTED** [review]
AdamC{
  "name": "Page Redder",
  "description": "Make the current page red",
  "version": "2.0",
  "permissions": [
    "activeTab"
  ],
  "background": {
    "scripts": ["background.js"],
    "persistent": false
  },
  "browser_action": {
    "default_title": "Make this page red"
  },
  "manifest_version": 2
}mv2-archive/api/browserAction/print/manifest.jsonmv2-archive/tutorials/oauth_tutorial_complete/oauth.jsmv2-archive/api/browserAction/print/background.jsanady:patch-1

**Pull request merged**
