### PR TITLE
Manga Cam

### PR DESCRIPTION
**Pull request by ikarienator**
# Manga Camera

Chrome Packaged App with `videoCapture` permission can query user media without a warning. It is also possible to process the image captured by a video camera using WebGL. You can then save the pictures you take to the the sync file system. The pictures will be synced among your devices.
## APIs
- [Runtime](http://developer.chrome.com/apps/app.runtime.html)
- [Window](http://developer.chrome.com/apps/app.window.html)
- [Sync File Systesm](http://developer.chrome.com/apps/syncFileSystem.html)
- [videoCapture](http://developer.chrome.com/apps/manifest.html#permissions)

### CODE REVIEW

**Comment by sntpolanco** [comment]
@ikarienator Would you be interested in selling me the chrome extension?

**Comment by ikarienator** [comment]
@sntpolanco Transferring ownership of an chrome app has always seems like a security issue to me. So no.

**Comment by sntpolanco** [comment]
What if I walk you through the update we will want to make. Keep the app under your name. And simply rent or lease it from you. This way you have full & clear picture.

Sent from my mobile; pls excuse typos

Santo Polanco
(M) 917-770-0171
Skype: sntpolanco

**Comment by ikarienator** [comment]
@sntpolanco This repository is owned by Google Chrome Team.

**Pull request merged**
