### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by gabrielduque**

### CODE REVIEW

**Comment by rios1223** [comment]
Thank you for helping

**Comment by baebhie** [comment]
Please approve my request and update all my application

**Comment by baebhie** [comment]
Update all my application

**Comment by htatkyaww** [comment]
Good

**Comment by rios1223** [comment]
I have issues

**Comment by htatkyaww** [comment]
+1

**Comment by rios1223** [comment]
Yes

**Comment by Hutchind85** [comment]
Hi just wanted to touch base and make sure that ur request for the update pull had gone tho. 

Any questions just reach out 
Daniel-John Hutchinson

**Pull request closed without merging**
